language: node_js
node_js:
  - "10"
  - "9"
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - nvm install-latest-npm
  - if [ -n "${ESLINT-}" ]; then npm uninstall --no-save eslint-config-airbnb-base && npm install --no-save "eslint@${ESLINT}"; fi
script:
  - if [ "${FLOW-}" = true ]; then npm run flow; fi
  - if [ "${LINT-}" = true ]; then npm run lint; fi
  - if [ "${TEST-}" = true ]; then npm run test:ci; fi
after_success:
  - if [ "${TEST-}" = true ]; then npm run coveralls; fi
sudo: false
env:
  global:
    - TEST=true
  matrix:
    - ESLINT=6
    - ESLINT=5
    - ESLINT=4
matrix:
  fast_finish: true
  include:
    - node_js: "node"
      env: FLOW=true TEST=false
    - node_js: "node"
      env: LINT=true TEST=false
